/**
 * @module database/adapters/sysmara-orm/adapter
 * Implements the standard DatabaseAdapter interface for the SysMARA ORM.
 * Wraps the SysmaraORM, SchemaGenerator, MigrationEngine, and Repository
 * into the unified adapter contract used by the framework's database layer.
 */

import type { DatabaseAdapter } from '../../adapter.js';
import type { GeneratedFile } from '../../../compiler/capability-compiler.js';
import type { SystemSpecs, CapabilitySpec } from '../../../types/index.js';
import { generateSchema } from './schema-generator.js';
import { MigrationEngine } from './migration-engine.js';

/**
 * Converts a snake_case or kebab-case name to PascalCase.
 *
 * @param name - The input name
 * @returns PascalCase string
 */
function toPascalCase(name: string): string {
  return name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Converts a snake_case or kebab-case name to camelCase.
 *
 * @param name - The input name
 * @returns camelCase string
 */
function toCamelCase(name: string): string {
  const pascal = toPascalCase(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Maps a SysMARA field type to a TypeScript type string.
 *
 * @param fieldType - The SysMARA field type
 * @returns The TypeScript type string
 */
function mapTsType(fieldType: string): string {
  switch (fieldType.toLowerCase()) {
    case 'string':
    case 'text':
    case 'enum':
    case 'uuid':
      return 'string';
    case 'number':
    case 'integer':
    case 'float':
    case 'decimal':
    case 'bigint':
      return 'number';
    case 'boolean':
    case 'bool':
      return 'boolean';
    case 'date':
    case 'datetime':
    case 'timestamp':
      return 'Date';
    case 'json':
      return 'Record<string, unknown>';
    default:
      return 'string';
  }
}

/**
 * Generates a TypeScript repository file that uses SysmaraRepository
 * for a given capability and its entities.
 *
 * @param capability - The capability to generate a repository for
 * @param allSpecs - All system specs for entity field resolution
 * @returns The TypeScript source code
 */
function generateRepositorySource(capability: CapabilitySpec, allSpecs: SystemSpecs): string {
  const capPascal = toPascalCase(capability.name);
  const entityMap = new Map(allSpecs.entities.map((e) => [e.name, e]));

  // Generate entity interfaces
  const interfaces: string[] = [];
  const repoMethods: string[] = [];

  for (const entityName of capability.entities) {
    const entity = entityMap.get(entityName);
    if (!entity) continue;

    const ifaceName = toPascalCase(entityName);
    const fields = entity.fields.map((f) => {
      const tsType = mapTsType(f.type);
      const optional = !f.required ? '?' : '';
      return `  ${toCamelCase(f.name)}${optional}: ${tsType};`;
    });

    interfaces.push(`/** Entity interface for "${entityName}". */\nexport interface ${ifaceName} {\n${fields.join('\n')}\n}`);

    repoMethods.push(`
  /**
   * Returns a SysmaraRepository for the "${entityName}" entity,
   * scoped to the "${capability.name}" capability.
   *
   * @param orm - The SysmaraORM instance
   * @returns A typed SysmaraRepository<${ifaceName}>
   */
  static ${toCamelCase(entityName)}Repository(orm: SysmaraORM): SysmaraRepository<${ifaceName}> {
    return orm.repository<${ifaceName}>('${entityName}', '${capability.name}');
  }`);
  }

  return `// ============================================================
// GENERATED BY SYSMARA ORM
// Source: capability:${capability.name}
// Edit Zone: generated
// DO NOT EDIT — this file will be regenerated
// ============================================================

import type { SysmaraORM } from '../../src/database/adapters/sysmara-orm/orm.js';
import type { SysmaraRepository } from '../../src/database/adapters/sysmara-orm/repository.js';

${interfaces.join('\n\n')}

/**
 * Repository factory for the "${capability.name}" capability.
 * Provides typed data-access methods for: ${capability.entities.join(', ')}.
 */
export class ${capPascal}Repository {
${repoMethods.join('\n')}
}
`;
}

/**
 * SysMARA ORM database adapter implementation.
 * Wraps the AI-first ORM to implement the standard DatabaseAdapter interface.
 *
 * - `generateSchema()` produces raw SQL CREATE TABLE statements
 * - `generateMigration()` uses the MigrationEngine for impact-aware diffs
 * - `generateRepository()` generates TypeScript wrappers using SysmaraRepository
 */
export const sysmaraOrmAdapter: DatabaseAdapter = {
  name: 'sysmara-orm',

  /**
   * Generates SQL schema files from system specifications.
   * Produces a single SQL file with CREATE TABLE statements for all entities,
   * including constraints, foreign keys, and provider-specific types.
   *
   * @param specs - The complete system specifications
   * @returns An array of generated schema files
   */
  generateSchema(specs: SystemSpecs): GeneratedFile[] {
    // Default to postgresql — the adapter config isn't threaded through
    // the DatabaseAdapter interface, matching the pattern of other adapters
    const sqlContent = generateSchema(specs, 'postgresql');

    return [
      {
        path: 'sysmara-orm/schema.sql',
        content: sqlContent,
        source: 'database:sysmara-orm',
        zone: 'generated',
      },
    ];
  },

  /**
   * Generates impact-aware migration files by diffing two SystemSpecs versions.
   * Produces a SQL migration file with risk analysis, affected capability tracking,
   * and a machine-readable migration plan JSON.
   *
   * @param prev - The previous system specifications
   * @param next - The updated system specifications
   * @returns An array of generated migration files
   */
  generateMigration(prev: SystemSpecs, next: SystemSpecs): GeneratedFile[] {
    const engine = new MigrationEngine('postgresql');
    const plan = engine.diff(prev, next);
    const sql = engine.generateSQL(plan);
    const impact = engine.analyzeImpact(plan, next);
    const timestamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);

    return [
      {
        path: `sysmara-orm/migrations/${timestamp}_migration.sql`,
        content: sql,
        source: 'database:sysmara-orm',
        zone: 'generated',
      },
      {
        path: `sysmara-orm/migrations/${timestamp}_migration.plan.json`,
        content: JSON.stringify(
          {
            plan: {
              steps: plan.steps,
              affectedCapabilities: plan.affectedCapabilities,
              affectedInvariants: plan.affectedInvariants,
              riskLevel: plan.riskLevel,
              requiresReview: plan.requiresReview,
            },
            impact,
            generatedAt: new Date().toISOString(),
          },
          null,
          2,
        ),
        source: 'database:sysmara-orm',
        zone: 'generated',
      },
    ];
  },

  /**
   * Generates TypeScript repository files for a specific capability.
   * Produces a typed repository factory that wraps SysmaraRepository
   * with entity-specific interfaces.
   *
   * @param capability - The capability to generate repository code for
   * @returns An array of generated repository files
   */
  generateRepository(capability: CapabilitySpec): GeneratedFile[] {
    // Build a minimal SystemSpecs for repository generation
    // In practice, the full specs would be available via the ORM instance
    const minimalSpecs: SystemSpecs = {
      entities: [],
      capabilities: [capability],
      policies: [],
      invariants: [],
      modules: [],
      flows: [],
      safeEditZones: [],
      glossary: [],
    };

    const content = generateRepositorySource(capability, minimalSpecs);

    return [
      {
        path: `generated/repositories/${capability.name}.repository.ts`,
        content,
        source: `capability:${capability.name}`,
        zone: 'generated',
      },
    ];
  },
};

/**
 * Creates a SysMARA ORM adapter with full system specs available for
 * repository generation. This variant produces richer repository output
 * with complete entity type information.
 *
 * @param specs - The complete system specifications
 * @returns A DatabaseAdapter with full spec awareness
 */
export function createSysmaraOrmAdapter(specs: SystemSpecs): DatabaseAdapter {
  return {
    ...sysmaraOrmAdapter,
    generateRepository(capability: CapabilitySpec): GeneratedFile[] {
      const content = generateRepositorySource(capability, specs);
      return [
        {
          path: `generated/repositories/${capability.name}.repository.ts`,
          content,
          source: `capability:${capability.name}`,
          zone: 'generated',
        },
      ];
    },
  };
}
