/**
 * @module database/adapters/prisma
 * Prisma adapter for the SysMARA database layer.
 * Converts entity specifications into Prisma schema files,
 * migration placeholders, and typed repository classes.
 */

import type { DatabaseAdapter } from '../adapter.js';
import type { GeneratedFile } from '../../compiler/capability-compiler.js';
import type { SystemSpecs, EntitySpec, EntityField, CapabilitySpec } from '../../types/index.js';

/**
 * Converts a snake_case or kebab-case name to PascalCase for Prisma model names.
 *
 * @param name - The input name (e.g., "user", "billing_cycle")
 * @returns PascalCase string (e.g., "User", "BillingCycle")
 */
function toPascalCase(name: string): string {
  return name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Converts a snake_case or kebab-case name to camelCase.
 *
 * @param name - The input name
 * @returns camelCase string
 */
function toCamelCase(name: string): string {
  const pascal = toPascalCase(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Maps a SysMARA field type to a Prisma scalar type.
 *
 * @param field - The entity field to map
 * @returns The Prisma type string
 */
function mapPrismaType(field: EntityField): string {
  switch (field.type.toLowerCase()) {
    case 'string':
      return 'String';
    case 'number':
    case 'integer':
      return 'Int';
    case 'float':
    case 'decimal':
      return 'Float';
    case 'boolean':
    case 'bool':
      return 'Boolean';
    case 'date':
    case 'datetime':
    case 'timestamp':
      return 'DateTime';
    case 'json':
      return 'Json';
    default:
      return 'String';
  }
}

/**
 * Checks whether a field has a "unique" constraint.
 *
 * @param field - The entity field to inspect
 * @returns True if the field has a unique constraint
 */
function isUnique(field: EntityField): boolean {
  return field.constraints?.some((c) => c.type === 'unique') ?? false;
}

/**
 * Generates a Prisma model block for a single entity.
 *
 * @param entity - The entity specification
 * @param allEntities - All entities for resolving references
 * @returns The Prisma model string
 */
function generatePrismaModel(entity: EntitySpec, allEntities: EntitySpec[]): string {
  const modelName = toPascalCase(entity.name);
  const entityNames = new Set(allEntities.map((e) => e.name));
  const lines: string[] = [];

  lines.push(`model ${modelName} {`);

  for (const field of entity.fields) {
    const parts: string[] = [];
    const fieldName = toCamelCase(field.name);

    // Check if this field references another entity (e.g., owner_id → user)
    const refEntityName = field.name.replace(/_id$/, '');
    const isReference = field.name.endsWith('_id') && entityNames.has(refEntityName);

    if (field.name === 'id') {
      parts.push(`  ${fieldName}`);
      parts.push('String');
      parts.push('@id @default(uuid())');
    } else if (field.name === 'created_at') {
      parts.push(`  ${fieldName}`);
      parts.push('DateTime');
      parts.push('@default(now())');
    } else if (field.name === 'updated_at') {
      parts.push(`  ${fieldName}`);
      parts.push('DateTime');
      parts.push('@updatedAt');
    } else {
      parts.push(`  ${fieldName}`);
      const prismaType = mapPrismaType(field);
      const nullable = !field.required ? '?' : '';
      parts.push(`${prismaType}${nullable}`);

      if (isUnique(field)) {
        parts.push('@unique');
      }

      // Map default values from constraints
      const defaultConstraint = field.constraints?.find((c) => c.type === 'min' || c.type === 'max');
      if (defaultConstraint === undefined) {
        // no default from constraints
      }
    }

    lines.push(parts.join('  '));

    // Add relation field after the foreign key field
    if (isReference) {
      const relModelName = toPascalCase(refEntityName);
      const relFieldName = toCamelCase(refEntityName);
      lines.push(`  ${relFieldName}  ${relModelName}  @relation(fields: [${fieldName}], references: [id])`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}

/**
 * Generates a complete schema.prisma file content from system specs.
 *
 * @param specs - The complete system specifications
 * @returns The full schema.prisma content
 */
function generatePrismaSchema(specs: SystemSpecs): string {
  const header = `// ============================================================
// GENERATED BY SYSMARA DATABASE ADAPTER (Prisma)
// DO NOT EDIT — this file will be regenerated
// ============================================================

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`;

  const models = specs.entities
    .map((entity) => generatePrismaModel(entity, specs.entities))
    .join('\n\n');

  return header + '\n' + models + '\n';
}

/**
 * Prisma database adapter implementation.
 * Converts SysMARA entity specifications into Prisma schema files,
 * migration placeholders, and typed repository classes.
 */
export const prismaAdapter: DatabaseAdapter = {
  name: 'prisma',

  generateSchema(specs: SystemSpecs): GeneratedFile[] {
    const schemaContent = generatePrismaSchema(specs);
    return [
      {
        path: 'prisma/schema.prisma',
        content: schemaContent,
        source: 'database:prisma',
        zone: 'generated',
      },
    ];
  },

  generateMigration(_prev: SystemSpecs, next: SystemSpecs): GeneratedFile[] {
    const timestamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
    const migrationName = `${timestamp}_sysmara_migration`;
    const entityNames = next.entities.map((e) => toPascalCase(e.name));

    const content = `-- ============================================================
-- GENERATED BY SYSMARA DATABASE ADAPTER (Prisma)
-- Migration: ${migrationName}
-- DO NOT EDIT — this file will be regenerated
-- ============================================================
-- Models: ${entityNames.join(', ')}
--
-- This is a placeholder migration file.
-- Run \`npx prisma migrate dev\` to generate the actual SQL migration.
--
`;

    return [
      {
        path: `prisma/migrations/${migrationName}/migration.sql`,
        content,
        source: 'database:prisma',
        zone: 'generated',
      },
    ];
  },

  generateRepository(capability: CapabilitySpec): GeneratedFile[] {
    // We need specs to resolve entity references, but the interface only passes
    // the capability. Generate a repository with the entity names available.
    const repoContent = generatePrismaRepositoryStandalone(capability);
    return [
      {
        path: `generated/repositories/${capability.name}.repository.ts`,
        content: repoContent,
        source: `capability:${capability.name}`,
        zone: 'generated',
      },
    ];
  },
};

/**
 * Generates a repository file from a capability without full system specs.
 * Uses only the entity names listed in the capability.
 *
 * @param capability - The capability specification
 * @returns The TypeScript repository source
 */
function generatePrismaRepositoryStandalone(capability: CapabilitySpec): string {
  const repoMethods: string[] = [];

  for (const entityName of capability.entities) {
    const pascalName = toPascalCase(entityName);
    const camelName = toCamelCase(entityName);

    repoMethods.push(`
  /** Find a ${entityName} by ID. */
  async find${pascalName}ById(id: string) {
    return this.prisma.${camelName}.findUnique({ where: { id } });
  }

  /** Find all ${entityName} records matching a filter. */
  async findMany${pascalName}(where: Record<string, unknown> = {}) {
    return this.prisma.${camelName}.findMany({ where });
  }

  /** Create a new ${entityName}. */
  async create${pascalName}(data: Record<string, unknown>) {
    return this.prisma.${camelName}.create({ data });
  }

  /** Update a ${entityName} by ID. */
  async update${pascalName}(id: string, data: Record<string, unknown>) {
    return this.prisma.${camelName}.update({ where: { id }, data });
  }

  /** Delete a ${entityName} by ID. */
  async delete${pascalName}(id: string) {
    return this.prisma.${camelName}.delete({ where: { id } });
  }`);
  }

  const capPascal = toPascalCase(capability.name);

  return `// ============================================================
// GENERATED BY SYSMARA DATABASE ADAPTER (Prisma)
// Source: capability:${capability.name}
// Edit Zone: generated
// DO NOT EDIT — this file will be regenerated
// ============================================================

/**
 * Repository for the "${capability.name}" capability.
 * Provides typed data-access methods for: ${capability.entities.join(', ')}.
 */
export class ${capPascal}Repository {
  private prisma: any;

  constructor(prismaClient: any) {
    this.prisma = prismaClient;
  }
${repoMethods.join('\n')}
}
`;
}
