/**
 * @module generators/docker
 * Generates Docker-related files (docker-compose.yml, Dockerfile, .dockerignore)
 * based on the selected database provider.
 */

import type { GeneratedTextFile } from './types.js';
import type { DatabaseProvider } from '../database/adapter.js';
import { requiresDocker } from './types.js';

function dbService(provider: DatabaseProvider): string {
  if (provider === 'postgresql') {
    return `  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: sysmara
      POSTGRES_PASSWORD: sysmara
      POSTGRES_DB: sysmara_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sysmara"]
      interval: 5s
      timeout: 5s
      retries: 5`;
  }

  if (provider === 'mysql') {
    return `  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sysmara
      MYSQL_USER: sysmara
      MYSQL_PASSWORD: sysmara
      MYSQL_DATABASE: sysmara_dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "sysmara", "-psysmara"]
      interval: 5s
      timeout: 5s
      retries: 5`;
  }

  return '';
}

/**
 * Generates docker-compose.yml for local development.
 * Includes the database service for PostgreSQL/MySQL, or just the app for SQLite.
 */
export function generateDockerCompose(provider: DatabaseProvider): GeneratedTextFile {
  const hasDb = requiresDocker(provider);
  const dbBlock = dbService(provider);
  const dependsOn = hasDb ? `\n    depends_on:\n      db:\n        condition: service_healthy` : '';
  const volumesBlock = hasDb ? `\nvolumes:\n  db_data:` : '';

  const content = `# Generated by SysMARA — local development environment
services:
${hasDb ? dbBlock + '\n\n' : ''}  app:
    build: .
    ports:
      - "\${PORT:-3000}:3000"
    env_file:
      - .env.local${dependsOn}
    volumes:
      - .:/app
      - /app/node_modules
${volumesBlock}
`;

  return { path: 'docker-compose.yml', content };
}

/**
 * Generates a production-ready multi-stage Dockerfile.
 */
export function generateDockerfile(): GeneratedTextFile {
  const content = `# Generated by SysMARA — production Dockerfile
FROM node:20-alpine AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

# Build
FROM base AS build
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
RUN npx sysmara build

# Production
FROM base AS production
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs && \\
    adduser --system --uid 1001 sysmara
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app .
USER sysmara
EXPOSE 3000
CMD ["node", "app/server.js"]
`;

  return { path: 'Dockerfile', content };
}

/**
 * Generates .dockerignore to keep Docker context small.
 */
export function generateDockerignore(): GeneratedTextFile {
  const content = `node_modules
dist
.git
.github
.framework
.env
.env.local
.env.*.local
coverage
*.tsbuildinfo
.DS_Store
`;

  return { path: '.dockerignore', content };
}
